#cloud-config

hostname: ertis25
manage_etc_hosts: true
apt_preserve_sources_list: true

users:
  - name: ertis
    primary-group: users
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users,docker,adm,dialout,audio,plugdev,netdev,video
    ssh-import-id: None
    lock_passwd: true
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDMv8ipbSz7GSR1rxqVQ7PBHUANlAcUEl2ehyCDdfpU0xgjW2jtfrre3fa8tIyzYQf90Erjz+UwqGqUlhNsfLyevccl/pNDiTUELYgqkamnB7z/0iLTdfU/fjPlaG3QqzwavjvWH8tY6PSzFtHkNEEhnd58/KhFxueQWvhNiK3+V/gl1v2Zt42svgmQzNgvxcjUhBc9uTXLfKCjXsnnD9K7Hqbflk7h8tKAXiEEFH+6KdkDucB8HhKUqbv2gD2CO46TuCOfg7dMW7xCv4VXg4WZ5I3dPzaPT0LAbe3Nbmp6H+0pR+DbMuj/1g9zF0r0Ouv+ke2W+Yw2nOLCsZKv8KiX cristian@MacBook-Pro-de-Cristian.local
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDXEUMxmV+OGsbV7C3cgzGuxLquk43rlivUoaMqernMkizNrzarNi56svHsyu84BrJoFymcuOPOKZIgQRygBL+Mwdbe5lps1bOfacIfbRrhg7CUsSIKr+3BbVijutKh15ZFuc/e5YYovjinqz+GHq3zYngOc2cvANpGN5bnldqhDvdv8bS7DZhWo/4S63rRm8mJjJnVoLuOp5NGAIu7mVW8JUiNHzdaiYOgx1pqulHLAD0YqRp3fXCHm4/PE3B1uyDIDLiUQFy6kH3sjQ+1qfbz9e2mQScQ7pT++c07Q72jMWaoevnaS2dcFw0WeUZnR4Z/xfXhQ5/3CtgNbD3c2IX8dzGZ3RalUh5kuXKhkSl3gq8VpgW5OuKlGAZza3J/8eYg7mpGjc6R/vVMxq5CjgPu6L5B65Pf6h+Rle40S+jfnqxoiBiSU9/wxyfa9Hr9bSJVwH2BSLJeqTDi8D80ZGTb2BsUUb3eVglCKq7QbnNPrfiG+TT1Zeu81v+M37AAnRW3tIYUHWactHKGeiLYUJmZS7Pzk5eyCPN64hAOUViVA4XYKLlZTBAuLWYNM1//LqiL0hWgb0TKcoT0K5k8ZuM2zD3hn4+feNwQKJKZlJcSwRf523Rwmby17t3VwiMHrW4EW5IfnxPRa55cByM9pvQ/Qx+q+7oDh1mZiJZsP9Jvpw== danielr.torresruiz@icloud.com
package_upgrade: false

write_files:
  - content: |
      persistent
      # Generate Stable Private IPv6 Addresses instead of hardware based ones
      slaac private

      # static IP configuration:
      interface eth0
      static ip_address=192.168.49.203/23
      # static ip6_address=fd51:42f8:caae:d92e::ff/64
      static routers=192.168.49.252
      static domain_name_servers=192.168.42.3 150.214.40.11

    path: /etc/dhcpcd.conf
# These commands will be ran once on first boot only
runcmd:
  - 'systemctl restart avahi-daemon'
  - 'sudo ip link set wlan0 down'